apiVersion: v1
kind: Namespace
metadata:
  name: prod-apps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod-apps
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:mysql://mysql-service:3306/mon_app_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: prod-apps
type: Opaque
stringData:
  MYSQL_PASSWORD: "UserPasswordJava987"