apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: prod-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false # 🔐 Sécurité
      containers:
      - name: frontend
        image: saadaouisalaheddine/mon-frontend:1.0.0 # 🏷️ Version explicite
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "256Mi" # 💾 Espace disque
          limits:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod-apps
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: ClusterIP